In [ ]:
from numpy import array
import pandas as pd
import numpy
from sklearn.model_selection import KFold


import numpy as np
import matplotlib.pyplot as plt
import time 
import matplotlib.pyplot as plt
df=pd.read_csv('/content/Ocscaled.csv', sep=',',header=None)

In [ ]:
list_data = df.to_numpy().tolist()
print(list_data)
print(type(list_data))
long_data=[]
for i in range(len(list_data)):
  long_data.append([])
  for k in range(2):
    long_data[i].append(list_data[i][k])
print(long_data)
N_data=[]
for i in range(len(list_data)):
  N_data.append(list_data[i][2])
print(N_data)


[[17.895, 73.40100000000001, 0.5404], [17.895, 73.40100000000001, 0.56061], [17.895, 73.402, 0.33838], [17.895, 73.403, 0.88384], [17.895, 73.403, 0.89394], [17.895, 73.404, 0.70202], [17.895, 73.404, 0.75758], [17.895, 73.404, 0.89394], [17.895, 73.405, 0.50505], [17.895, 73.406, 0.75758], [17.895, 73.407, 0.8383799999999999], [17.895, 73.40899999999999, 0.79293], [17.895, 73.434, 0.33838], [17.895, 73.48100000000001, 0.75758], [17.895, 73.482, 0.47475], [17.913, 74.903, 0.31313], [17.913, 74.64, 0.36869], [17.929000000000002, 75.36399999999999, 0.16162], [17.942, 74.883, 0.24747], [17.947, 74.874, 0.19192], [17.947, 74.875, 0.43433999999999995], [17.949, 74.846, 0.23736999999999997], [17.949, 74.847, 0.29798], [17.95, 74.847, 0.43433999999999995], [17.95, 74.846, 0.14645999999999998], [17.95, 74.847, 0.37374], [17.95, 74.852, 0.4798], [17.951, 74.846, 0.11615999999999999], [17.951, 74.848, 0.22221999999999997], [17.951, 74.848, 0.44948999999999995], [17.951, 74.85600000000001, 0.1464

In [ ]:
from scipy.spatial import distance
from collections import OrderedDict 
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

def smape(A, F):
    return 100/len(A) * np.sum(2 * np.abs(F - A) / (np.abs(A) + np.abs(F)))


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
# import numpy as np
# data = array(list_data)
# kfold = KFold(5, True, 1)


# val_dict = dict()
# val_dict['rmse']=[]
# val_dict['r2']=[]
# val_dict['smape']=[]
# val_dict['mae']=[]

# for train, test in kfold.split(data):
#   rmse_list =[]
#   smape_list=[]
#   mae_list =[]
#   r2_list = []
#   distances =[]
#   train_coordinates =[]
#   for i in range(len(data[train])):
#      train_coordinates.append([])
#      for k in range(2):
#         train_coordinates[i].append(data[train][i][k])
#   # print(data[train][0][0])
#   test_coordinates =[]
#   test_values =[]
#   for i in range(len(data[test])):
#      test_coordinates.append([])
#      for k in range(2):
#        test_coordinates[i].append(data[test][i][k])
#      test_values.append(data[test][i][2])
#   # print(test_coordinates)
  
#   dist_dict=dict()
#   predicted_values =[]
#   for i in range(len(data[test])):
#     distances = (distance.cdist([test_coordinates[i]],train_coordinates , "euclidean" ))
    
#     for j in range(len(distances[0])):
#       dist_dict[j]=distances[0][j]
   
    
#     dist_dict = {k: v for k, v in sorted(dist_dict.items(), key=lambda item: item[1])}
   
#     input_data =[]
#     input_values =[]
#     for k,j in dist_dict.items():
#       if(len(input_data) >900):
#         break
#       if(j > 0.1 ):
#         input_data.append( data[train][k][2]/j)
#         input_values.append(data[test][i][2])  
#     print(np.array(input_data).reshape(-1,1))
#     print("****************************")
#     print(np.array(input_values).reshape(-1,1))
#     print("--------------------------------------")
#     svr_rbf = SVR(kernel='rbf', C=1, gamma=0.1, epsilon=.1)
#     svr_rbf.fit( np.array(input_data).reshape(-1,1),np.array(input_values).reshape(-1,1))

#     predicted_values.append( svr_rbf.predict(np.array(([data[test][i][0] , data[test][i][1]])).reshape(-1,1)))
#     print(predicted_values)
  
#   rmse_list.append( sqrt(mean_squared_error(predicted_values , test_values )))
#   smape_list.append(smape(predicted_values , test_values ))
#   r2_list.append(r2_score(predicted_values , test_values ))
#   mae_list.append(mean_absolute_error(predicted_values , test_values ))

#   val_dict[rmse].append(rmse_list)
#   val_dict[r2].append(r2_list)
#   val_dict[mae].append(mae_list)
#   val_dict[smape].append(smape_list)
  






[[3.53469863]
 [0.63256088]
 [0.29999182]
 [1.17512447]
 [0.56054691]
 [0.91557377]
 [0.60940689]
 [1.65570006]
 [1.13899873]
 [0.55046117]
 [0.68211254]
 [0.81757392]
 [0.86984752]
 [1.46654961]
 [0.89526916]
 [0.32328989]
 [0.54944288]
 [1.64566591]
 [0.74739889]
 [1.38599487]
 [1.66059478]
 [0.54406832]
 [1.05435986]
 [0.57628575]
 [1.36045914]
 [0.52063379]
 [1.75630583]
 [1.35132465]
 [1.45375939]
 [1.5280222 ]
 [0.9533067 ]
 [1.53023401]
 [1.48994708]
 [1.256194  ]
 [0.47311893]
 [0.57381169]
 [0.87825158]
 [1.50165242]
 [1.22948171]
 [0.33646067]
 [1.3539128 ]
 [0.74495931]
 [0.98654092]
 [0.33277546]
 [0.68982722]
 [0.13525124]
 [1.48558901]
 [0.98112767]
 [0.87039228]
 [0.50089291]
 [0.68128077]
 [1.08172439]
 [1.44033944]
 [0.78485367]
 [1.42039848]
 [1.38429029]
 [0.49324056]
 [0.75756713]
 [1.17602152]
 [1.4273799 ]
 [1.42609347]
 [0.13178923]
 [0.9789559 ]
 [0.30838391]
 [0.69981142]
 [0.41503768]
 [0.87495985]
 [0.08270309]
 [0.57818673]
 [0.80201916]
 [1.11131529]
 [0.83

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3.55153612]
 [0.63272098]
 [0.30025402]
 [1.17722829]
 [0.56193641]
 [0.9177688 ]
 [0.61086322]
 [1.65904633]
 [1.14087721]
 [0.55136455]
 [0.68323256]
 [0.81892523]
 [1.4687438 ]
 [0.86997668]
 [0.8967615 ]
 [0.32360428]
 [0.55034062]
 [1.6484157 ]
 [0.74856813]
 [1.38663708]
 [1.66274175]
 [0.54496257]
 [1.05602595]
 [0.57737986]
 [1.36296224]
 [0.5210683 ]
 [1.75837801]
 [1.35265484]
 [1.45546676]
 [1.52982849]
 [0.95495772]
 [1.53278484]
 [1.49224107]
 [1.25764089]
 [0.47356081]
 [0.57481474]
 [0.87934417]
 [1.50432657]
 [1.23156952]
 [0.33714386]
 [1.35670162]
 [0.74537612]
 [0.98820078]
 [0.33315565]
 [0.69095231]
 [0.13546457]
 [0.98315591]
 [1.48642814]
 [0.8717106 ]
 [0.50162283]
 [0.68246381]
 [1.0828444 ]
 [1.44185153]
 [0.78600691]
 [1.421849  ]
 [1.38570394]
 [0.49393749]
 [0.75834349]
 [1.43012923]
 [1.17723507]
 [1.42849629]
 [0.1320052 ]
 [0.9794294 ]
 [0.30896471]
 [0.70112941]
 [0.41570393]
 [0.87643336]
 [0.08277356]
 [0.57911213]
 [0.80352586]
 [0.83158361]
 [1.11

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3.67120953]
 [0.63355442]
 [0.30200419]
 [1.19187627]
 [0.57181888]
 [0.93336417]
 [0.62120927]
 [1.68268303]
 [1.15404112]
 [0.55769617]
 [0.69108535]
 [0.82840238]
 [0.90723287]
 [1.48407622]
 [0.87070552]
 [0.55663777]
 [0.32576507]
 [1.66772142]
 [0.75675763]
 [0.55123886]
 [1.67767555]
 [1.39088451]
 [1.06770515]
 [0.58510359]
 [1.38061242]
 [1.77275593]
 [0.52404184]
 [1.46731273]
 [1.36182109]
 [1.54236516]
 [0.96657902]
 [1.55071603]
 [1.50832122]
 [1.26767816]
 [0.58187964]
 [0.47660219]
 [0.88694729]
 [1.52318039]
 [1.2462669 ]
 [0.34198539]
 [1.37647718]
 [0.99988768]
 [0.69886568]
 [0.74818573]
 [0.99754449]
 [0.13696338]
 [0.33579689]
 [0.88096079]
 [0.50673821]
 [0.69080596]
 [1.492093  ]
 [1.09060329]
 [0.79409438]
 [1.45233368]
 [1.44959368]
 [0.49881906]
 [1.44542899]
 [0.1335257 ]
 [1.43189716]
 [1.39549666]
 [0.76372243]
 [1.18564588]
 [0.31307443]
 [0.71045555]
 [0.42039268]
 [0.88682081]
 [0.98260838]
 [0.81418786]
 [0.58562489]
 [0.08325897]
 [0.83960275]
 [1.11

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[4.7804605 ]
 [0.61362265]
 [1.3235304 ]
 [0.3098311 ]
 [0.69062785]
 [1.11845395]
 [0.74385955]
 [1.94375443]
 [1.28589485]
 [0.62129127]
 [0.92441344]
 [0.77034903]
 [1.0139858 ]
 [0.67010075]
 [1.8661351 ]
 [0.6206464 ]
 [1.63268872]
 [1.57215388]
 [0.6155251 ]
 [0.83854963]
 [1.18564321]
 [1.60717263]
 [0.39802325]
 [1.0901261 ]
 [0.65763022]
 [1.73831591]
 [1.16641648]
 [1.72788223]
 [1.81481365]
 [1.6709352 ]
 [1.40295805]
 [0.34276511]
 [1.90107955]
 [1.1248837 ]
 [1.67250769]
 [1.5729779 ]
 [1.65470408]
 [0.78244259]
 [0.78171304]
 [0.95741683]
 [0.15258665]
 [1.35716372]
 [0.35986014]
 [0.81662572]
 [1.43679424]
 [0.93566542]
 [0.97591138]
 [1.62869956]
 [0.54618954]
 [0.55850547]
 [0.14979834]
 [0.50114326]
 [1.40732247]
 [0.99979813]
 [0.87664852]
 [0.86042754]
 [0.47035594]
 [0.51014776]
 [0.65507465]
 [0.54795574]
 [0.35985531]
 [1.20947368]
 [0.3834373 ]
 [1.17498167]
 [0.77864228]
 [1.07609857]
 [1.15893367]
 [1.61363812]
 [0.76755898]
 [1.03988719]
 [1.54545719]
 [0.92

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[2.27633533]
 [2.75843151]
 [1.14949548]
 [1.59601511]
 [2.46635728]
 [1.42687017]
 [1.7542358 ]
 [2.82760318]
 [1.13507919]
 [0.55452776]
 [1.41822898]
 [2.06552416]
 [1.77733803]
 [1.41305294]
 [1.05097049]
 [2.12582453]
 [2.19563251]
 [1.76251281]
 [1.40032587]
 [1.39907507]
 [1.68054192]
 [1.96454549]
 [1.17883752]
 [2.16545344]
 [1.45799652]
 [2.01513546]
 [1.94467908]
 [0.67819366]
 [1.00513664]
 [0.23345945]
 [0.95626237]
 [0.88240246]
 [0.46377332]
 [0.53201069]
 [1.08604597]
 [0.66780012]
 [1.97916535]
 [0.94263058]
 [1.6323847 ]
 [1.76576751]
 [1.83257413]
 [1.21321055]
 [1.62510994]
 [1.48648025]
 [0.89126697]
 [1.54822335]
 [1.2726025 ]
 [3.24436832]
 [1.20205198]
 [0.72503772]
 [0.97369987]
 [0.65566471]
 [1.7404748 ]
 [0.69910559]
 [1.60094394]
 [0.45070402]
 [1.73457839]
 [0.78845283]
 [1.21607923]
 [1.39531799]
 [1.32697934]
 [2.15742602]
 [1.48175939]
 [1.59404824]
 [0.78579968]
 [2.19923482]
 [0.91649018]
 [0.58117702]
 [1.31760588]
 [1.58561075]
 [0.71465019]
 [1.62

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1.75355328]
 [2.19750691]
 [1.72477006]
 [0.68259413]
 [1.99902084]
 [4.26771616]
 [2.24083587]
 [0.95102202]
 [0.94963406]
 [2.22268636]
 [3.92057536]
 [1.36622183]
 [1.78772111]
 [2.75036329]
 [4.70823651]
 [2.73618068]
 [4.53491328]
 [2.5891109 ]
 [3.55332246]
 [3.54283783]
 [3.25910115]
 [2.14931128]
 [2.69293242]
 [1.63569642]
 [4.17402686]
 [3.21906527]
 [1.44760129]
 [2.53325747]
 [2.12608042]
 [2.65409028]
 [2.91703626]
 [2.90786677]
 [1.56116071]
 [2.49783947]
 [5.30622053]
 [2.61728555]
 [1.41913959]
 [3.81161344]
 [4.33683064]
 [2.60844606]
 [1.54675079]
 [3.65676209]
 [3.9044776 ]
 [3.11452575]
 [3.24268788]
 [2.18987746]
 [3.89084987]
 [1.26550505]
 [1.91818595]
 [3.35686857]
 [2.96269586]
 [1.78548432]
 [1.26146174]
 [1.39198337]
 [2.4343934 ]
 [2.30262898]
 [1.77711394]
 [3.85292869]
 [3.05862196]
 [2.54164414]
 [0.98846151]
 [1.2459831 ]
 [2.7907662 ]
 [1.24449783]
 [1.2398515 ]
 [2.77595991]
 [2.26125928]
 [1.6208627 ]
 [2.51247535]
 [2.63516206]
 [3.77669353]
 [1.85

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[4.48683096]
 [1.75675438]
 [2.20756816]
 [2.74903356]
 [2.71500467]
 [3.97162576]
 [1.65379037]
 [2.77385791]
 [2.15187098]
 [0.64001996]
 [3.38008316]
 [2.28134918]
 [2.14116378]
 [0.90929916]
 [3.76854241]
 [0.90603772]
 [1.30762645]
 [1.70745709]
 [2.63492842]
 [2.6295879 ]
 [4.50148597]
 [2.608546  ]
 [3.13481063]
 [1.40332365]
 [2.45577298]
 [2.06105022]
 [1.57156543]
 [3.35736892]
 [4.25591251]
 [3.28625095]
 [4.17772307]
 [3.79009561]
 [1.99972526]
 [2.7583633 ]
 [1.7322121 ]
 [1.85777741]
 [3.25115227]
 [2.73833023]
 [1.7260029 ]
 [3.86497723]
 [4.99559721]
 [1.34310765]
 [0.9640913 ]
 [2.21769109]
 [3.72000571]
 [2.45861768]
 [2.08276149]
 [2.83044567]
 [2.94818931]
 [2.44987716]
 [2.20031605]
 [1.20304058]
 [1.19948486]
 [1.44670059]
 [1.32151731]
 [1.19671881]
 [2.55763371]
 [4.77906848]
 [2.17748389]
 [2.89969173]
 [1.18201341]
 [2.64793604]
 [2.51959491]
 [1.17378531]
 [2.63087442]
 [2.50664477]
 [1.77209833]
 [1.28557628]
 [5.13873329]
 [3.80362645]
 [3.07348508]
 [1.75

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[4.4949    ]
 [2.81691451]
 [4.07153321]
 [2.71951923]
 [1.69338257]
 [0.65567893]
 [2.19448643]
 [2.18202663]
 [0.92798691]
 [3.84190139]
 [0.92498604]
 [1.33404799]
 [2.70846145]
 [1.7425684 ]
 [2.6845045 ]
 [2.68276316]
 [4.59251455]
 [3.19393997]
 [2.65409028]
 [3.30316806]
 [2.23163512]
 [1.42741774]
 [2.49793689]
 [2.09643701]
 [3.43184254]
 [1.60127035]
 [2.88989622]
 [4.35559763]
 [3.3695714 ]
 [2.04918862]
 [4.25292629]
 [3.84967722]
 [2.80100758]
 [3.96326917]
 [1.88892667]
 [3.30566417]
 [5.10689362]
 [1.75900432]
 [1.75552408]
 [1.36652409]
 [3.79400898]
 [2.25707534]
 [2.51256466]
 [0.97876443]
 [2.12480339]
 [2.88504974]
 [1.22660563]
 [1.48040061]
 [1.35338112]
 [2.99972926]
 [2.49270567]
 [1.22437482]
 [1.21838658]
 [2.5985221 ]
 [2.96923764]
 [2.21563898]
 [1.20580994]
 [2.69899213]
 [2.6873913 ]
 [1.19803931]
 [2.55558856]
 [2.18008215]
 [2.54409131]
 [1.80475901]
 [1.31069575]
 [5.23488006]
 [3.8789531 ]
 [1.79244653]
 [1.66167252]
 [3.12062115]
 [2.98982433]
 [3.58

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[2.80898442]
 [4.14066568]
 [1.72133214]
 [2.74540482]
 [0.66639509]
 [2.22737847]
 [2.21416064]
 [0.94204599]
 [3.89880933]
 [0.93906941]
 [1.35402318]
 [1.76879158]
 [2.72335189]
 [2.72266972]
 [4.660829  ]
 [2.70745506]
 [3.23988899]
 [2.69117463]
 [2.94792256]
 [3.48419628]
 [1.44713698]
 [2.53244494]
 [2.12539849]
 [4.42343005]
 [1.62416991]
 [2.23189658]
 [3.30226536]
 [3.42332216]
 [2.08147238]
 [4.31174487]
 [3.90021274]
 [4.02600054]
 [2.84345029]
 [5.18323972]
 [1.91419655]
 [3.34988703]
 [1.78184486]
 [1.77914624]
 [1.3850147 ]
 [3.84798406]
 [2.54972629]
 [2.28777969]
 [2.15515103]
 [0.99133704]
 [2.92548492]
 [1.3741091 ]
 [1.50275296]
 [1.24386932]
 [1.24198948]
 [3.04009939]
 [2.52625231]
 [1.23494939]
 [3.01431937]
 [2.63218111]
 [2.24529312]
 [1.22279489]
 [2.73633183]
 [2.72612301]
 [1.21502782]
 [2.58705621]
 [1.82911059]
 [2.57582792]
 [1.32877759]
 [5.30580833]
 [3.93265478]
 [2.18961603]
 [1.81775431]
 [1.69060677]
 [3.15961955]
 [3.03093323]
 [3.63474284]
 [1.42

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[2.80898442]
 [4.14066568]
 [1.72133214]
 [2.74540482]
 [0.66639509]
 [2.22737847]
 [2.21416064]
 [0.94204599]
 [3.89880933]
 [0.93906941]
 [1.35402318]
 [1.76879158]
 [2.72335189]
 [2.72266972]
 [4.660829  ]
 [2.70745506]
 [3.23988899]
 [2.69117463]
 [2.94792256]
 [3.48419628]
 [1.44713698]
 [2.53244494]
 [2.12539849]
 [4.42343005]
 [1.62416991]
 [2.23189658]
 [3.30226536]
 [3.42332216]
 [2.08147238]
 [4.31174487]
 [3.90021274]
 [4.02600054]
 [2.84345029]
 [5.18323972]
 [1.91419655]
 [3.34988703]
 [1.78184486]
 [1.77914624]
 [1.3850147 ]
 [3.84798406]
 [2.54972629]
 [2.28777969]
 [2.15515103]
 [0.99133704]
 [2.92548492]
 [1.3741091 ]
 [1.50275296]
 [1.24386932]
 [1.24198948]
 [3.04009939]
 [2.52625231]
 [1.23494939]
 [3.01431937]
 [2.63218111]
 [2.24529312]
 [1.22279489]
 [2.73633183]
 [2.72612301]
 [1.21502782]
 [2.58705621]
 [1.82911059]
 [2.57582792]
 [1.32877759]
 [5.30580833]
 [3.93265478]
 [2.18961603]
 [1.81775431]
 [1.69060677]
 [3.15961955]
 [3.03093323]
 [3.63474284]
 [1.42

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[4.17254258]
 [2.77738506]
 [1.73387269]
 [2.74385403]
 [0.67142366]
 [2.24043658]
 [0.9478346 ]
 [2.22659439]
 [0.94496835]
 [3.92126143]
 [1.36219761]
 [1.77970922]
 [2.7391848 ]
 [4.6891005 ]
 [2.73849066]
 [2.99614855]
 [3.25802483]
 [2.70488828]
 [3.50792932]
 [2.68406885]
 [4.4555749 ]
 [1.4543844 ]
 [2.5451277 ]
 [2.13604272]
 [1.63331876]
 [3.45070488]
 [2.09766455]
 [2.21398325]
 [3.27476934]
 [4.33483425]
 [4.05842687]
 [2.86371779]
 [3.91795182]
 [5.21907527]
 [1.92364024]
 [3.36641371]
 [1.78981439]
 [1.78814525]
 [2.5670767 ]
 [1.39218993]
 [3.87131919]
 [2.2999076 ]
 [2.16845847]
 [0.99569778]
 [2.94261696]
 [1.38455722]
 [1.51373252]
 [1.25129223]
 [1.24992444]
 [3.05595514]
 [2.53942807]
 [1.241677  ]
 [3.03715382]
 [2.64454323]
 [2.25707534]
 [1.23036539]
 [2.7524427 ]
 [2.7443518 ]
 [1.22279489]
 [1.71831969]
 [2.59771721]
 [1.83935779]
 [1.33675287]
 [2.58705621]
 [5.33608834]
 [3.95665086]
 [1.82954448]
 [3.1738985 ]
 [3.04944046]
 [2.18116751]
 [3.65197715]
 [1.43

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1.76233306]
 [2.76805824]
 [2.76739563]
 [0.68237159]
 [2.27359225]
 [0.96204363]
 [2.25892576]
 [0.9592199 ]
 [3.97859619]
 [1.38237495]
 [1.80623088]
 [2.7795239 ]
 [4.75815538]
 [2.77759116]
 [3.05856832]
 [3.3043104 ]
 [2.74208274]
 [3.56120998]
 [4.52485823]
 [1.47415405]
 [2.57972397]
 [2.16507824]
 [1.65640354]
 [3.50593302]
 [2.68113372]
 [2.13078651]
 [4.39404746]
 [4.1229397 ]
 [2.90706855]
 [3.96847484]
 [5.29693868]
 [1.94899833]
 [3.41079093]
 [2.21270803]
 [1.81264154]
 [3.27163108]
 [1.81187807]
 [2.60495516]
 [3.92601376]
 [1.41078876]
 [2.19924145]
 [2.33082673]
 [1.40581657]
 [1.53660767]
 [2.98352919]
 [1.00825888]
 [1.26877736]
 [1.26782625]
 [3.09659056]
 [2.57319517]
 [3.08339765]
 [1.25838489]
 [2.67828202]
 [2.28694458]
 [1.24760947]
 [2.79026211]
 [2.78383386]
 [1.24007369]
 [1.74924895]
 [2.62911757]
 [1.86397578]
 [1.35509257]
 [5.40786129]
 [2.61879932]
 [4.01116732]
 [1.85531532]
 [3.09118931]
 [3.21297957]
 [2.95860697]
 [3.69753423]
 [1.45333507]
 [2.18

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: ignored

In [ ]:
import numpy as np
data = array(list_data)
kfold = KFold(5, True, 1)


val_dict = dict()
val_dict['rmse']=[]
val_dict['r2']=[]
val_dict['smape']=[]
val_dict['mae']=[]
dist_dict=dict()
predicted_values =[]

distances = (distance.cdist(data,data, "euclidean" ))
print(distances)
print(len(distances))
svr_dict=dict()
svr_dict['svr_input']=[]
svr_dict['svr_values']=[]

count=0
for i in range(len(distances)):
    for j in range(len(distances[i])):
      dist_dict[j]=distances[i][j]
    dist_dict = {k: v for k, v in sorted(dist_dict.items(), key=lambda item: item[1])}
    input_data =[]
    input_values =[]
    for k,j in dist_dict.items():
      if(len(input_data) >399):
        break
      if(j > 0.1 ):
        input_data.append( data[k][2]/j)
    input_values.append(data[i][2])
    count=count+1
    print(count)
    svr_dict['svr_input'].append(input_data)
    svr_dict['svr_values'].append(input_values)
log_df = pd.DataFrame(svr_dict)
log_df.to_csv('/content/gdrive/My Drive/oc_features_399_Svr.csv')

    



Streaming output truncated to the last 5000 lines.
20943
20944
20945
20946
20947
20948
20949
20950
20951
20952
20953
20954
20955
20956
20957
20958
20959
20960
20961
20962
20963
20964
20965
20966
20967
20968
20969
20970
20971
20972
20973
20974
20975
20976
20977
20978
20979
20980
20981
20982
20983
20984
20985
20986
20987
20988
20989
20990
20991
20992
20993
20994
20995
20996
20997
20998
20999
21000
21001
21002
21003
21004
21005
21006
21007
21008
21009
21010
21011
21012
21013
21014
21015
21016
21017
21018
21019
21020
21021
21022
21023
21024
21025
21026
21027
21028
21029
21030
21031
21032
21033
21034
21035
21036
21037
21038
21039
21040
21041
21042
21043
21044
21045
21046
21047
21048
21049
21050
21051
21052
21053
21054
21055
21056
21057
21058
21059
21060
21061
21062
21063
21064
21065
21066
21067
21068
21069
21070
21071
21072
21073
21074
21075
21076
21077
21078
21079
21080
21081
21082
21083
21084
21085
21086
21087
21088
21089
21090
21091
21092
21093
21094
21095
21096
21097
21098
21099
21100
2

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive
