In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/scaledNForkrig.csv', sep=',',header=None)

In [ ]:
df.head()

,0,1,2
0,17.895,73.401,0.63157
1,17.895,73.401,0.65262
2,17.895,73.402,0.39998
3,17.895,73.404,0.82105
4,17.895,73.404,0.88421


In [ ]:
list_data = df.to_numpy().tolist()
print(list_data)
print(type(list_data))
# long_data=[]
# for i in range(len(list_data)):
#   long_data.append([])
#   for k in range(2):
#     long_data[i].append(list_data[i][k])
# print(long_data)
# N_data=[]
# for i in range(len(list_data)):
#   N_data.append(list_data[i][2])

# print(N_data)

[[17.895, 73.40100000000001, 0.63157], [17.895, 73.40100000000001, 0.65262], [17.895, 73.402, 0.39998], [17.895, 73.404, 0.82105], [17.895, 73.404, 0.88421], [17.895, 73.405, 0.58946], [17.895, 73.406, 0.88421], [17.895, 73.407, 0.97895], [17.895, 73.40899999999999, 0.9263100000000001], [17.895, 73.434, 0.39998], [17.895, 73.48100000000001, 0.88421], [17.895, 73.482, 0.55788], [17.913, 74.903, 0.3684], [17.913, 74.64, 0.16764], [17.929000000000002, 75.36399999999999, 0.50876], [17.942, 74.883, 0.21986999999999998], [17.947, 74.874, 0.22804000000000002], [17.947, 74.875, 0.50876], [17.949, 74.846, 0.28068000000000004], [17.949, 74.847, 0.35086], [17.95, 74.847, 0.47367], [17.95, 74.846, 0.17540999999999998], [17.95, 74.847, 0.43858], [17.95, 74.852, 0.56139], [17.951, 74.846, 0.14032], [17.951, 74.848, 0.26313000000000003], [17.951, 74.848, 0.5263], [17.951, 74.85600000000001, 0.17540999999999998], [17.951, 74.876, 0.10522999999999999], [17.951, 74.854, 0.43858], [17.951, 74.854, 0.4385

In [ ]:
from scipy.spatial import distance
from collections import OrderedDict 
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt
def smape(A, F):
    return 1/len(A) * np.sum(2 * np.abs(F - A) / (np.abs(A) + np.abs(F)))
def manualr2(A,F):
  correlation_matrix = np.corrcoef(A,F)
  correlation_xy = correlation_matrix[0,1]
  r_squared = correlation_xy**2
  return r_squared 


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
x=df.drop([2], axis = 1).values
y= df[2].values.reshape(-1,1)

In [ ]:
print(x)

[[17.895 73.401]
 [17.895 73.401]
 [17.895 73.402]
 ...
 [20.597 75.914]
 [20.598 75.423]
 [20.598 75.595]]


In [ ]:
print(y)

[[0.63157]
 [0.65262]
 [0.39998]
 ...
 [0.29822]
 [0.24559]
 [0.42103]]


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
print(len(x_train[0]))

2


In [ ]:
svr_rbf = SVR(kernel='linear', C=1, gamma=0.1, epsilon=.1)
svr_rbf.fit( x_train,y_train.ravel())

SVR(C=1, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred=svr_rbf.predict(x_test)
print(y_pred)

[0.24592911 0.26916899 0.19002423 ... 0.2811127  0.21330004 0.26032212]


In [ ]:

print(len(y_pred))

5162


In [ ]:
print(y_test)
output =[]
for i in range(len(y_test)):
  output.append(y_test[i][0])
print(output)

[[0.097714]
 [0.31577 ]
 [0.15035 ]
 ...
 [0.23807 ]
 [0.12278 ]
 [0.35086 ]]
[0.097714, 0.31577, 0.15035, 0.13364, 0.24559, 0.40349, 0.14144, 0.094205, 0.25895999999999997, 0.25227, 0.20956, 0.033527, 0.14668, 0.078499, 0.68771, 0.12278, 0.29822, 0.19646, 0.15035, 0.22804000000000002, 0.40349, 0.13614, 0.24841, 0.039233, 0.17808, 0.12996, 0.24559, 0.33331, 0.28068000000000004, 0.4227, 0.10178999999999999, 0.061063, 0.20956, 0.10189, 0.19139, 0.22303, 0.18325, 0.09604299999999999, 0.1204, 0.13355999999999998, 0.17282, 0.15064, 0.24434, 0.10472999999999999, 0.19954000000000002, 0.17549, 0.35086, 0.15787, 0.1069, 0.2105, 0.14667, 0.13097, 0.030168, 0.19384, 0.71344, 0.12303, 0.19546, 0.31577, 0.28068000000000004, 0.12194, 0.49121000000000004, 0.45611999999999997, 0.33331, 0.0086553, 0.088524, 0.24559, 0.31737, 0.6491100000000001, 0.11787, 0.15192, 0.22804000000000002, 0.18336, 0.19296, 0.12215, 0.23806999999999998, 0.2199, 0.087689, 0.7017399999999999, 0.066953, 0.17174, 0.1963, 0.16789,

In [ ]:
svrresults={'lat':[],'long':[],'actual':[],'predicted':[]}
for i in range(len(x_test)):
    svrresults['lat'].append(x_test[i][0])
    svrresults['long'].append(x_test[i][1])
svrresults['actual']=output
svrresults['predicted']=y_pred
print(svrresults['lat'])
log_df = pd.DataFrame(svrresults)
log_df.to_csv('/content/drive/My Drive/n/n_final_results_latlon.csv')

[19.028, 19.53, 18.355, 18.469, 19.646, 18.541, 18.314, 18.433, 18.29, 19.273, 18.494, 19.651, 18.178, 18.202, 19.194000000000003, 18.283, 19.524, 18.487000000000002, 18.206, 19.812, 19.504, 18.186, 18.323, 18.975, 18.28, 18.205, 18.225, 18.555999999999997, 18.449, 19.752, 18.357, 18.355, 18.486, 19.241, 18.404, 18.691, 18.385, 18.315, 18.47, 18.435, 18.343, 18.241, 18.347, 18.232, 18.324, 18.180999999999997, 19.674, 19.500999999999998, 18.407, 19.474, 18.414, 18.456, 18.537, 18.835, 19.192999999999998, 18.209, 18.257, 19.63, 19.317, 18.352, 18.48, 18.511, 19.874000000000002, 19.297, 19.278, 19.862000000000002, 20.387, 19.729, 18.174, 18.738, 18.76, 19.416, 20.314, 18.358, 19.194000000000003, 18.378, 18.113, 18.657, 18.327, 18.209, 18.835, 19.91, 18.438, 19.055, 19.512, 18.064, 18.808, 18.284000000000002, 18.006, 18.038, 19.404, 18.253, 18.389, 19.949, 18.359, 18.596, 19.07, 18.658, 18.351, 19.509, 18.372, 18.381, 18.836, 19.867, 18.257, 19.829, 18.227, 18.498, 19.109, 18.574, 18.261, 

In [ ]:
val_dict = dict()
val_dict['rmse']=[]
val_dict['r2']=[]
val_dict['manualr2']=[]
val_dict['smape']=[]
val_dict['mae']=[]
rmse_list =[]
r2_list =[]
mae_list =[]
smape_list =[]
rmse_list.append( sqrt(mean_squared_error(y_pred ,output )))
smape_list.append(smape(y_pred , output ))
r2_list.append(r2_score(y_pred , output ))
mae_list.append(mean_absolute_error(y_pred , output ))

val_dict['rmse'].append(rmse_list)
val_dict['r2'].append(svr_rbf.score(x_test, output))
val_dict['manualr2'].append(manualr2(y_pred,output))
val_dict['mae'].append(mae_list)
val_dict['smape'].append(smape_list)
log_df = pd.DataFrame(val_dict)
log_df.to_csv('/content/drive/My Drive/n/n_val_r_latlon.csv')


In [ ]:
from sklearn.model_selection import KFold
data = np.array(list_data)
# prepare cross validation
kfold = KFold(5, True, 1)
val_dict = dict()
val_dict['rmse']=[]
val_dict['r2']=[]
val_dict['manualr2']=[]
val_dict['smape']=[]
val_dict['mae']=[]
rmse_list =[]
r2_list =[]
mae_list =[]
smape_list =[]
count = 0
for train, test in kfold.split(data):
  count = count + 1
  X_train=[]
  y_train=[]
  x_test =[]
  y_test =[]
  y_values =[]
  # print('train: %s, test: %s' % (data[train], data[test]))
  for i in range(len(data[train])):
    X_train.append([data[train][i][0] , data[train][i][1]])
    y_train.append([data[train][i][2]])
    
    # print(X[i])
    # print(y[i])
  for i in range(len(data[test])):
    x_test.append([data[test][i][0] , data[test][i][1]])
    y_test.append([data[test][i][2]])
    y_values.append(data[test][i][2])
  svr_rbf = SVR(kernel='linear', C=1, gamma=0.1, epsilon=.1)
  svr_rbf.fit(X_train,y_train)
  y_pred=svr_rbf.predict(x_test)
  svr_results={'lat':[],'long':[],'actual':[],'predicted':[]}
  for i in range(len(x_test)):
    svr_results['lat'].append(x_test[i][0])
    svr_results['long'].append(x_test[i][1])
  svr_results['actual'] = y_values
  svr_results['predicted'] =  y_pred
  log_df = pd.DataFrame(svr_results)
  log_df.to_csv('/content/drive/My Drive/n/svr_results_latlon_5fold_' + str(count) +'.csv')

  rmse_list.append( sqrt(mean_squared_error(y_pred , y_values )))
  smape_list.append(smape(y_pred , y_values ))
  # r2_list.append(r2_score(y_pred , y_values ))
  r2_list.append(svr_rbf.score(x_test, y_values))
  mae_list.append(mean_absolute_error(y_pred , y_values ))
val_dict['rmse'].append(rmse_list)
val_dict['r2'].append(r2_list)
val_dict['smape'].append(smape_list)
val_dict['manualr2'].append(manualr2(y_pred,y_values))
val_dict['mae'].append(mae_list)
log_df = pd.DataFrame(val_dict)
log_df.to_csv('/content/drive/My Drive/n/svr_val_results_5_fold_lat_long.csv')


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:

from sklearn.model_selection import KFold
data = np.array(list_data)
# prepare cross validation
kfold = KFold(10, True, 1)
val_dict = dict()
val_dict['rmse']=[]
val_dict['r2']=[]
val_dict['manualr2']=[]
val_dict['smape']=[]
val_dict['mae']=[]
rmse_list =[]
r2_list =[]
mae_list =[]
smape_list =[]
count = 0
for train, test in kfold.split(data):
  count = count + 1
  X_train=[]
  y_train=[]
  x_test =[]
  y_test =[]
  y_values =[]
  # print('train: %s, test: %s' % (data[train], data[test]))
  for i in range(len(data[train])):
    X_train.append([data[train][i][0] , data[train][i][1]])
    y_train.append([data[train][i][2]])
    
    # print(X[i])
    # print(y[i])
  for i in range(len(data[test])):
    x_test.append([data[test][i][0] , data[test][i][1]])
    y_test.append([data[test][i][2]])
    y_values.append(data[test][i][2])
  svr_rbf = SVR(kernel='linear', C=1, gamma=0.1, epsilon=.1)
  svr_rbf.fit(X_train,y_train)
  y_pred=svr_rbf.predict(x_test)
  svr_results={'lat':[],'long':[],'actual':[],'predicted':[]}
  for i in range(len(x_test)):
    svr_results['lat'].append(x_test[i][0])
    svr_results['long'].append(x_test[i][1])
  svr_results['actual'] = y_values
  svr_results['predicted'] =  y_pred
  log_df = pd.DataFrame(svr_results)
  log_df.to_csv('/content/drive/My Drive/n/svr_results_latlon_10fold_' + str(count) +'.csv')

  rmse_list.append( sqrt(mean_squared_error(y_pred , y_values )))
  smape_list.append(smape(y_pred , y_values ))
  # r2_list.append(r2_score(y_pred , y_values ))
  r2_list.append(svr_rbf.score(x_test, y_values))
  mae_list.append(mean_absolute_error(y_pred , y_values ))
val_dict['rmse'].append(rmse_list)
val_dict['r2'].append(r2_list)
val_dict['smape'].append(smape_list)
val_dict['manualr2'].append(manualr2(y_pred,y_values))
val_dict['mae'].append(mae_list)
log_df = pd.DataFrame(val_dict)
log_df.to_csv('/content/drive/My Drive/n/svr_val_results_10_fold_lat_long.csv')